/*
 * Interrupt_Drv_Cfg.h
 *
 *  Created on: 2024年10月10日
 *      Author: alex_ruan
 */

#ifndef GENERATED_INC_INTERRUPT_DRV_CFG_H_
#define GENERATED_INC_INTERRUPT_DRV_CFG_H_

#define INTERRUPT_DRV_CFG_H_VENDOR_ID 0x00B3U
#define INTERRUPT_DRV_CFG_H_AR_RELEASE_MAJOR_VERSION 4U
#define INTERRUPT_DRV_CFG_H_AR_RELEASE_MINOR_VERSION 6U
#define INTERRUPT_DRV_CFG_H_SW_MAJOR_VERSION 1U
#define INTERRUPT_DRV_CFG_H_SW_MINOR_VERSION 2U
#define INTERRUPT_DRV_CFG_H_SW_PATCH_VERSION 1U

#endif /* GENERATED_INC_INTERRUPT_DRV_CFG_H_ */
